" {{{ compatibility
if has("win32") && !has("nvim")
    source $VIMRUNTIME/vimrc_example.vim
    " source $VIMRUNTIME/mswin.vim
    " behave mswin
endif
" }}} compatibility
" {{{ plugins
if has("win32")
    call plug#begin('~/vimfiles/plugged')
else
    call plug#begin('~/.vim/plugged')
endif

let g:plug_timeout=120
Plug 'plasticboy/vim-markdown'
Plug 'mhinz/vim-signify'
Plug 'qpkorr/vim-bufkill'
Plug 'unblevable/quick-scope'
" Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'felikz/ctrlp-py-matcher'
Plug 'andrewradev/splitjoin.vim'
Plug 'FooSoft/vim-argwrap'
" if has ("nvim")
"     Plug 'benekastah/neomake'
" endif
Plug 'scrooloose/syntastic'
" Plug 'w0rp/ale'
Plug 'terryma/vim-multiple-cursors'
Plug 'terryma/vim-expand-region'
Plug 'easymotion/vim-easymotion'
Plug 'markonm/traces.vim'
Plug 'aykamko/vim-easymotion-segments'
Plug 'godlygeek/tabular'
" Plug 'rking/ag.vim'
Plug 'mhinz/vim-grepper'
Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
Plug 'will133/vim-dirdiff'
Plug 'nelstrom/vim-visual-star-search'
Plug 'nelstrom/vim-qargs'
Plug 'alvan/vim-closetag'
Plug 'tommcdo/vim-exchange'
Plug 'ludovicchabant/vim-gutentags'
Plug 'qpkorr/vim-renamer'
Plug 'vim-scripts/matchit.zip'
" Plug 'davidhalter/jedi-vim'
Plug 'osse/double-tap'
Plug 'sickill/vim-pasta'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'kana/vim-operator-user' " recommended for clang-format
Plug 'rhysd/vim-clang-format'
Plug 'christoomey/vim-sort-motion'
Plug 'wellle/targets.vim'
Plug 'michaeljsmith/vim-indent-object'
Plug 'vim-scripts/ReplaceWithRegister'
" Plug 'reedes/vim-pencil'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-unimpaired'
" Plug 'tpope/vim-sleuth' " adjust shiftwidth and expandtab automatically
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/gv.vim'
if !has ("win32")
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    Plug 'shougo/vimproc', { 'do': 'make' }
else
    Plug 'vim-scripts/Windows-PowerShell-Syntax-Plugin'
    if !has("neovim")
        Plug 'kkoenig/wimproved.vim'
    endif
endif

" if has("win32")
"     " this file tells vim where the python library is
"     source ~/configs/vim/windows/python_setup.vim
" endif

if has ("python3")
    " plugins for UltiSnips and SuperTab support
    Plug 'sirver/ultisnips'
    Plug 'tomtom/tlib_vim'
    Plug 'marcWeber/vim-addon-mw-utils'
    Plug 'ervandew/supertab'
    "Plug 'othree/vim-autocomplpop'
    Plug 'vim-scripts/L9'
    " extra snippet
    Plug 'honza/vim-snippets'
endif

" tmux plugins
if !has("win32")
Plug 'edkolev/tmuxline.vim'
Plug 'benmills/vimux'
Plug 'christoomey/vim-tmux-navigator'
endif


" colorschemes
Plug 'morhetz/gruvbox'
Plug 'nanotech/jellybeans.vim'

" cmake syntax
Plug 'nickhutchinson/vim-cmake-syntax'

" unicode
Plug 'chrisbra/unicode.vim'

call plug#end()
" }}} plugins
" {{{ signify configuration
let g:signify_vcs_list = ['git', 'svn']
let g:signify_realtime = 0
" }}}
" {{{ tmux configuration
" enable support for timuxline in airline
let g:airline#extensions#tmuxline#enabled = 1
let g:tmuxline_powerline_separators = 1
"let g:tmuxline_separators = {
"    \ 'left' : '',
"    \ 'left_alt': '>',
"    \ 'right' : '',
"    \ 'right_alt' : '<',
"    \ 'space' : ' '}

let g:tmux_navigator_no_mappings = 1
if $TMUX != ''
    nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
    nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
    nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
    nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
    nnoremap <silent> <c-p> :TmuxNavigatePrevious<cr>
else
    nnoremap <silent> <c-h> <c-w>h
    nnoremap <silent> <c-j> <c-w>j
    nnoremap <silent> <c-k> <c-w>k
    nnoremap <silent> <c-l> <c-w>l
    nnoremap <silent> <c-p> <c-w>p
endif

" }}} tmux configuration
" {{{ ctrlp configuration
let g:ctrlp_working_path_mode = 0
let g:ctrlp_map = '<leader>e'
"let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_extensions = ['tag']
" Use The Silver Searcher if available
if executable('ag')
    " Use ag over grep
    set grepprg=ag\ --nogroup\ --nocolor
    " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
    let g:ctrlp_user_command = 'ag %s -l --nocolor
    \ --ignore .svn
    \ --ignore "**/*.pyc"
    \ --ignore tags
    \ --ignore cscope.out
    \ --ignore Session.vim
    \ -g ""'


    " Ag is sometimes fast enough that CtrlP doesn't need to cache
    " let g:ctrlp_use_caching = 0
endif
" }}} ctrlp configuration
"{{{ closetag configuration
" enable closetag for xml,html,htm,xhtml and ndb files
let g:closetag_filenames = "*.xml,*.html,*.htm,*.xhtml,*.ndb,*.2db,*.config,*.rss,*.scn,*.settings"
"}}} closetag configuration
"{{{ airline configuration
" always display airline
set laststatus=2
" disable the tabline
 let g:airline#extensions#tabline#enabled = 0
" show only the file name
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#tagbar#enabled = 0

" set jellybeans theme for airline
let g:airline_theme = 'jellybeans'
" use the patched fonts
let g:airline_powerline_fonts = 1
" disable whitespace detection
let g:airline#extensions#whitespace#enabled = 0
let g:airline#extensions#wordcount#enabled = 0
" disable arrows
"let g:airline_left_sep = ''
"let g:airline_left_alt_sep = ''
"let g:airline_right_sep = ''
"let g:airline_right_alt_sep = ''
"}}} airline configuration
"{{{ syntastic configuration
" disable syntastic active check by default
let g:syntastic_mode_map = {"mode": "passive"}
"}}} syntastic configuration
" {{{ goyo configuration
let g:goyo_width = 96
" }}}
" {{{ gugentags configuration
" let g:gutentags_ctags_exclude = ["linux-xlnx"]
" }}}
" {{{ quickscope configuration
" Trigger a highlight in the appropriate direction when pressing these keys:
let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
" }}}
"{{{ argwrap configuration
nnoremap <silent> gw :ArgWrap<CR>
"}}}
"{{{ grepper configuration
let g:grepper = {
      \ 'tools': ['git', 'ag', 'vimgrep'],
      \ 'vimgrep': {
      \   'grepprg':    "vim -es +'set nonu nornu | vimgrep /$*/ ** | cw | %p | qa'",
      \   'grepprgbuf': "vim -es +'set nonu nornu | vimgrep /$*/ $. | cw | %p | qa'",
      \   'grepformat': '%f|%l col %c|%m' }}
"}}}
"{{{ vim-pasta configuration
let g:pasta_disabled_filetypes = ['ctrlp']
"}}}
"{{{ custom commands and functions
function! RemoveTrailingWhitespacesFunction()
    execute "normal! mz"
    silent %s/\s\+$//ge
    execute "normal! `z"
endfunction
command! RemoveTrailingWhitespaces call RemoveTrailingWhitespacesFunction()
function! ShrugFunction()
    execute "normal i¯\\_(ツ)_/¯"
endfunction
command! Shrug call ShrugFunction()
" }}}
"{{{ autocmd
" set tab and indent configuration based on file type
if has("autocmd")
    "enable file type detection
    filetype on

    autocmd FileType c          setlocal ts=4 sts=4 sw=4 tw=100 cc=100 expandtab cindent comments ^=://
    autocmd FileType cpp        setlocal ts=4 sts=4 sw=4 tw=100 cc=100 expandtab cindent comments ^=:///
    autocmd FileType cmake      setlocal ts=4 sts=4 sw=4 tw=100 expandtab commentstring=#\ %s
    autocmd FileType cs         setlocal ts=4 sts=4 sw=4 tw=100 expandtab cindent comments ^=://
    autocmd FileType css        setlocal ts=4 sts=4 sw=4 expandtab
    autocmd FileType html       setlocal ts=4 sts=4 sw=4 expandtab
    autocmd FileType javascript setlocal ts=4 sts=4 sw=4 tw=100 expandtab
    autocmd FileType java       setlocal ts=8 sts=4 sw=4 tw=100 expandtab
    autocmd FileType json       setlocal ts=4 sts=4 sw=4 tw=100 expandtab
    autocmd FileType make       setlocal ts=8 sts=8 sw=8 tw=100 noexpandtab
    autocmd FileType python     setlocal ts=4 sts=4 sw=4 tw=100 expandtab autoindent
    autocmd FileType vim        setlocal ts=4 sts=4 sw=4 tw=100 expandtab
    autocmd FileType text       setlocal ts=4 sts=4 sw=4 tw=205 expandtab
    autocmd FileType xml        setlocal ts=4 sts=4 sw=4 noexpandtab

    " change de default comment style to c++ for c++ files
    autocmd FileType cpp,cs     setlocal commentstring=//\ %s

    " Treat the files with the following extentions as xml
    autocmd BufNewFile,BufRead *.rss,*.ndb,*.2db,*.config,*.scn setfiletype xml

    " Force this style for c++, since vim-sleuth misreads the initializer
    " list offset as the file general shiftwidth sometimes.
    " autocmd BufRead *.cpp,*.h setlocal ts=4 sts=4 sw=4 expandtab

    " Remove trailing whitespaces when saving
    " autocmd BufWritePre * call RemoveTrailingWhitespacesFunction()

    " Source the vimrc file after saving it
    " if has("win32")
    "     autocmd BufWritePost _vimrc source $MYVIMRC
    " else
    "     autocmd BufWritePost .vimrc source $MYVIMRC
    " endif

    " Fix the white bars on Windows, this is using the wimproved plugin
    if has("win32") && !has("nvim")
        autocmd GUIEnter * silent! WToggleClean
    endif
endif
"}}} autocmd
" {{{ wildignore
if has("win32")
    set wildignore+=*\\.git\\*,*\\.hg\\*,*\\.svn\\*,tags,cscope.out,*.pyc,*.sdf,*.opensdf,*.suo,Session.vim  " Windows ('noshellslash')
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,tags,cscope.out,*.pyc,Session.vim
endif
" }}}
" {{{ mappings

" map leader key to space
let mapleader="\<space>"

" edit the vimrc on a vertical split on leader v
nmap <leader>v :e $MYVIMRC<CR>

" map F12 to toggle NERDTree
noremap <silent> <F12> :NERDTreeToggle<CR>

" map F10 to toggle whitespace detection
noremap <silent> <F10> :AirlineToggleWhitespace<CR>:SyntasticToggleMode<CR>

" map F11 to toggle fullscreen on Windows
if has("win32") && !has("nvim")
    noremap <silent> <F11> :WToggleFullscreen<CR>
endif

" map F9 to toggle tag bar
noremap <silent> <F9> :TagbarToggle<CR>

" map F5 to toggle undotree
nnoremap <silent> <F5> :UndotreeToggle<CR>

" bubble text up and down with ctrl-up and down (requires unimpaired plugin)
" bubble single lines
nmap <C-Up> [e
nmap <C-Down> ]e
" bubble multiple lines
vmap <C-Up> [egv
vmap <C-Down> ]egv

" quick pairs
" imap <leader>' ''<ESC>i
" imap <leader>" ""<ESC>i
" imap <leader>( ()<ESC>i
" imap <leader>[ []<ESC>i

" enable using ctrl-numpad+ for incrementing
noremap <C-kPlus> <C-A>

" enable using ctrl-numpad- for decrementing
noremap <C-kMinus> <C-X>

" center after search
" nmap n nzz
" nmap N Nzz

" center after jump to next function
" nmap ]] ]]zz
" nmap [[ [[zz

" map Y to y$ (yank till end of line)
nmap Y y$

" map leader-s to buffer save.
nnoremap <leader>s :w<CR>

" map leader-S to save all buffers
nnoremap <leader>S :wa<CR>

" map space k and space j to buffer next and buffer previous
nnoremap <silent> <leader>k :bn<CR>
nnoremap <silent> <leader>j :bp<CR>

" map leader-t to CtrlPTag
nnoremap <leader>t :CtrlPTag<CR>

" map leader-l to CtrlPBuffer
nnoremap <leader>l :CtrlPBuffer<CR>

" map leader-x to delete buffer to vim-bufkill's BD command
nnoremap <silent> <leader>x :BD<CR>

" map leader-o to toggle .h/.cpp file (o for opposite)
map <leader>o :e %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>

" map leader g to fugitive.vim commands
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gl :GV<CR>
nnoremap <leader>gL :GV!<CR>
nnoremap <leader>gc :Gcommit<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gr :Gread<CR>
nnoremap <leader>gw :Gwrite<CR>

" map leader w to ctrl-w for window operations
nnoremap <leader>w <c-w>
if has("nvim")
tnoremap <leader>w <c-w>
endif

" quit terminal mode on ESC in neovim
if has("nvim")
tnoremap <Esc> <C-\><C-n>
endif

" }}} mappings
" {{{ folding
" reasonable folding
set foldenable
set foldlevelstart=0
set foldnestmax=10
nnoremap <leader>f za
set foldmethod=marker
" }}}
" {{{ misc

" Scroll all the way to the edge
set scrolloff=0

" load filetype plugins
filetype plugin on

" disable the tabline
set showtabline=0

" enable syntax highligting
syntax on

" find files recursively from the cwd. this should be added to the project
" vimrc, the the global one. keeping it here as a note
" set path+=**

" enable line numbers
set number

" enable relative line numbers
set relativenumber

" enable hidden buffers by default
set hidden

" don't create the ~filename files
"set nobackup

" store swap, backup and undo files in a central location instead of the
" current directory
if has("win32")
    set dir=~/vimswap//
    set backupdir=~/vimbackup//
    set undodir=~/vimundo//
else
    set dir=~/.vimswap//
    set backupdir=~/.vimbackup//
    set undodir=~/.vimundo//
endif

" turn off highlighted search by default, turn on only when needed.
set nohlsearch

" turn on incremental search (search as character are entered)
set incsearch

" always show at least one line above/below the cursor
set scrolloff=1

" redraw only when we need to
set lazyredraw

" briefly hightligh matching [{()}]
set showmatch

" match angle brackets
:set matchpairs+=<:>

" turn on virtual edit so we can navigate beyond the valid text
"set virtualedit=all

" turn on the wildmenu
set wildmenu

" disable line wrap
set nowrap

" easy switch to proper soft wrapping mode
command! -nargs=* Wrap set wrap linebreak nolist
command! -nargs=* NoWrap set nowrap nolinebreak

" enable cursorline
set cul

" open new split to rignt or bottom and move cursor to new split
set splitbelow
set splitright

" insert one space instead of two after a '.', '?' and '!' with a join command.
set nojoinspaces

" highlight last inserted text
nnoremap gV `[v`]

" disable startup screen
set shortmess=I

" setup the search such that if the pattern contains an uppercase letter, it
" is case sensitive, otherwise, it is not
set ignorecase
set smartcase

" show whitespaces when calling set list
if !has("nvim")
set encoding=utf-8
endif
scriptencoding=utf-8
set listchars=tab:>\ ,eol:¬,extends:>,precedes:<

" share clipboard with system
if !has("win32")
    if !has("nvim")
        set clipboard=unnamedplus
    else
        set clipboard=unnamed
    endif
else
    set clipboard=unnamed
endif
" }}}misc
" {{{ gui vs terminal
if has('gui_running')
    set guioptions-=T " remove tool bar
    set guioptions-=m " remove menu bar
    set guioptions-=r " remove righ-hand scroll bar
    set guioptions-=L " remove left-hand scroll bar
    " use the jellybeans color scheme
    set background=dark
    colorscheme jellybeans

    if has ("win32")
        " set guifont=Powerline_Consolas:h14:cANSI " works great on 16:9 screens
        set guifont=Powerline_Consolas:h13:cANSI " works great on 16:10 screens
    else
        set guifont=Inconsolata\ for\ Powerline\ Medium\ 13
    endif
    set linespace=1
else
    " Enable mouse support.
    set mouse=a
    set t_ut= "disable Background Color Erase (BCE)
    if !has("nvim")
        if !has("win32")
            set term=xterm-256color
        endif
        set t_Co=256
    endif
    set background=dark
    colorscheme jellybeans
endif

" }}} gui vs terminal
" {{{ external vimrc support
set exrc
set secure
" }}}
